INSERT INTO `{prefix}_mods` (`mid`, `name`, `icon`, `modfolder`, `steam_universe`) VALUES
(1, 'Web', 'web.png', 'NULL', '0'),
(2, 'Half-Life 2 Deathmatch', 'hl2dm.png', 'hl2mp', '0'),
(3, 'Counter-Strike: Source', 'csource.png', 'cstrike', '0'),
(4, 'Day of Defeat: Source', 'dods.png', 'dod', '0'),
(5, 'Insurgency: Source', 'ins.gif', 'insurgency', '0'),
(6, 'Dystopia', 'dys.gif', 'dystopia_v1', '0'),
(7, 'Hidden: Source', 'hidden.png', 'hidden', '0'),
(8, 'Half-Life 2 Capture the Flag', 'hl2ctf.png', 'hl2ctf', '0'),
(9, 'Pirates Vikings and Knights II', 'pvkii.gif', 'pvkii', '0'),
(10, 'Perfect Dark: Source', 'pdark.gif', 'pdark', '0'),
(11, 'The Ship', 'ship.gif', 'ship', '0'),
(12, 'Fortress Forever', 'hl2-fortressforever.gif', 'FortressForever', '0'),
(13, 'Team Fortress 2', 'tf2.png', 'tf', '0'),
(14, 'Zombie Panic', 'zps.gif', 'zps', '0'),
(15, "Garry's Mod", 'gmod.png', 'garrysmod', '0'),
(16, "Left 4 Dead", 'l4d.png', 'left4dead', '1'),
(17, "Left 4 Dead 2", 'l4d2.png', 'left4dead2', '1'),
(18, "CSPromod", 'cspromod.png', 'cspromod', '0'),
(19, "Alien Swarm", 'alienswarm.png', 'alienswarm', '0'),
(20, "E.Y.E: Divine Cybermancy", 'eye.png', 'eye', '0'),
(21, "Nuclear Dawn", 'nucleardawn.png', 'nucleardawn', '0'),
(22, "Counter-Strike: Global Offensive", 'csgo.png', 'csgo', '1'),
(23, 'Synergy', 'synergy.png', 'synergy', '0'),
(24, 'No More Room in Hell', 'nmrih.png', 'nmrih', '0'),
(25, 'Codename CURE', 'cure.png', 'cure', '0'),
(26, 'Counter-Strike 2', 'cs2.png', 'cs2', '1');

UPDATE `{prefix}_mods` SET `mid` = '0' WHERE `name` = 'Web';

INSERT INTO `{prefix}_settings` (`setting`, `value`) VALUES
('dash.intro.text', '<center><p>SourceBans успешно установлена.</p><p>Добро пожаловать!</p></center>'),
('dash.lognopopup', '0'),
('banlist.bansperpage', '20'),
('banlist.hideadminname', '0'),
('banlist.nocountryfetch', '0'),
('banlist.hideplayerips', '0'),
('bans.customreasons', ''),
('unban.customreasons', 'a:0:{}'),
('comms.customreasons', 'a:0:{}'),
('remove_comms.customreasons', 'a:0:{}'),
('config.password.minlength', '3'),
('config.debug', '0'),
('template.logo', 'images/icons/logo-material-admin.svg'),
('template.title', 'SourceBans'),
('config.enableprotest', '0'),
('config.enablesubmit', '0'),
('config.exportpublic', '0'),
('config.enablekickit', '1'),
('config.dateformat', 'd.m.Y в H:i'),
('config.dateformat_ver2', 'd.m.Y'),
('config.theme', 'new_box'),
('config.defaultpage', '0'),
('config.timezone', '3'),
('config.summertime', '0'),
('config.enablegroupbanning', '0'),
('config.enablefriendsbanning', '0'),
('config.enableadminrehashing', '1'),
('config.modgroup', '0'),
('protest.emailonlyinvolved', '0'),
('config.version', '530'),
('config.text_home', 'Добро пожаловать на сайт'),
('config.text_mon', 'У вас есть возможность управлять игроками через мониторинг'),
('config.text_acc', 'Успешный вход в систему!'),
('config.text_acc2', 'Подробно ознакомьтесь с данными на этой странице.'),
('template.global', '0'),
('dash.info_block', '0'),
('dash.info_block_text', ''),
('dash.info_vk', ''),
('dash.info_steam', ''),
('dash.info_yout', ''),
('dash.info_face', ''),
('dash.info_block_text_t', ''),
('page.adminlist', '0'),
('page.xleb', '1'),
('theme.style', 'blue'),
('theme.style.color', ''),
('theme.bg', ''),
('theme.bg.rep', 'inherit'),
('theme.bg.att', 'inherit'),
('theme.bg.pos', ''),
('theme.bg.size', ''),
('theme.splashscreen', '1'),
('theme.home.stats', '1'),
('config.home.comms', '1'),
('config.enableadmininfos', '1'),
('config.changeadmininfos', '1'),
('page.vay4er', '0'),
('page.footer.allow_show_data', '0'),
('feature.old_serverside', '0'),
('feature.map_autofetch', '1'),
('admin.warns', '1'),
('admin.warns.max', '3'),
('demoEnabled', '1'),
('smtp.enabled', '0'),
('smtp.username', ''),
('smtp.port', ''),
('smtp.host', ''),
('smtp.password', ''),
('smtp.charset', 'utf-8'),
('smtp.from', '');

INSERT INTO `{prefix}_admins` (
`aid`, `user`, `authid`, `password`, `gid`, `email`, `validate`, `extraflags`, `immunity`, `expired`)
VALUES (
NULL, 'CONSOLE', 'STEAM_ID_SERVER', '', '0', '', NULL, '0', 0, 0);

UPDATE `{prefix}_admins` SET `aid` = '0' WHERE `authid` = 'STEAM_ID_SERVER';

INSERT INTO `{prefix}_menu` (`id`, `text`, `description`, `url`, `system`, `enabled`, `newtab`, `priority`) VALUES
(1, '<i class=''zmdi zmdi-home zmdi-hc-fw''></i> Главная', 'Главная страница. Список серверов, последних банов и блоков.', 'index.php?p=home', 1, 1, 0, 1000),
(2, '<i class=''zmdi zmdi-input-composite zmdi-hc-fw''></i> Серверы', 'Список всех серверов и их текущий статус.', 'index.php?p=servers', 1, 1, 0, 999),
(3, '<i class=''zmdi zmdi-lock-outline zmdi-hc-fw''></i> Список банов', 'Список всех когда-либо выданных банов.', 'index.php?p=banlist', 1, 1, 0, 998),
(4, '<i class=''zmdi zmdi-mic-off zmdi-hc-fw''></i> Список мутов/гагов', 'Список всех когда-либо выданных мутов и гагов.', 'index.php?p=commslist', 1, 1, 0, 997),
(5, '<i class=''zmdi zmdi-plus-circle-o-duplicate zmdi-hc-fw''></i> Пожаловаться на игрока', 'Здесь вы можете оставить жалобу на игрока.', 'index.php?p=submit', 1, 0, 0, 996),
(6, '<i class=''zmdi zmdi-comment-edit zmdi-hc-fw''></i> Апелляция бана', 'Вы можете подать апелляцию бана, предоставив доказательства невиновности.', 'index.php?p=protest', 1, 0, 0, 995),
(7, '<i class=''zmdi zmdi-accounts zmdi-hc-fw''></i> Админлист', 'Список администраторов на доступных серверах.', 'index.php?p=adminlist', 1, 0, 0, 994);
